packages:
  - 'backend'
  - 'frontend'
  - 'admin'
  - 'docs'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  ffmpeg-static: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
